// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";

// UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

// Data reducer types
export const SET_STOCKFEEDS = "SET_STOCKFEEDS";
export const SET_STOCKFEED = "SET_STOCKFEED";
export const LIKE_STOCKFEED = "LIKE_STOCKFEED";
export const UNLIKE_STOCKFEED = "UNLIKE_STOCKFEED";
export const DELETE_STOCKFEED = "DELETE_STOCKFEED";
export const POST_STOCKFEED = "POST_STOCKFEED";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
